package:
  name: giropops-senhas
  description: Aplicacao Giropops Senhas
  version: 0.1.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - python3
      - python3-dev
      - py3-pip
      - py3-virtualenv

pipeline:
  - name: Build da app
    runs: |
      EXECDIR="${{targets.destdir}}/usr/bin"
      WEBAPPDIR="${{targets.destdir}}/app"
      
      mkdir -p "${EXECDIR}" "${WEBAPPDIR}" "${WEBAPPDIR}/templates/" "${WEBAPPDIR}/static/{css,js}"
      cp -a ./app.py "${WEBAPPDIR}/app.py"
      cp -a ./requirements.txt "${WEBAPPDIR}/requirements.txt"
      cp -a ./LICENSE "${WEBAPPDIR}/LICENSE"
      cp -a ./tailwind.config.js "${WEBAPPDIR}/tailwind.config.js"
      cp -a ./templates/. "${WEBAPPDIR}/templates/"
      cp -a ./static/. "${WEBAPPDIR}/static/"
      chmod +x "${WEBAPPDIR}/app.py"
      virtualenv "${WEBAPPDIR}/venv"
      
      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install -r requirements.txt"