version: '3'

env:
  IMAGE_NAME: giropops-senhas
  REGISTRY_USER: ricardosilva86
  COSIGN_KEY_PATH: ./desafio-pick

dotenv: [ .env, .env-docker ]

tasks:

  instalar-pre-reqs:
    dir: '{{.TASKFILE_DIR}}'
    preconditions:
      - sh: command -v brew
        msg: "Homebrew não está instalado. Por favor, instale-o antes de prosseguir. Visite https://brew.sh para mais informações."
      - sh: command -v docker
        msg: "Docker não está instalado. Por favor, instale-o antes de prosseguir. Visite https://docs.docker.com/get-docker/ para mais informações. Se você estiver no macOS ou no Linux, simplesmente execute o comando curl -fsSL get.docker.com | sh"
    cmds:
      - echo "Instalando pré-requisitos..."
      - brew install git
      - brew install go@1.23
      - brew install go-task
      - brew install helm@3
      - brew install cosign
      - brew install kubernetes-cli@1.31
      - docker image pull cgr.dev/chainguard/melange:latest
      - docker image pull cgr.dev/chainguard/apko:latest

  run:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Iniciando aplicação localmente..."
      - docker compose up -d

  stop:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Parando aplicação..."
      - docker compose down

  instalar-kyverno:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Instalando Kyverno..."
      - kubectl create -f https://github.com/kyverno/kyverno/releases/download/v1.11.1/install.yaml
    preconditions:
      - sh: sh -c "! kubectl get ns kyverno"
    silent: true

  instalar-politicas-kyverno:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Instalando políticas do Kyverno..."
      - helm uninstall politicas-kyverno --namespace kyverno || true
      - helm install politicas-kyverno politicas-kyverno/ --namespace kyverno

  instalar-prometheus:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Instalando a Stack de Monitoramento..."
      - git clone https://github.com/prometheus-operator/kube-prometheus
      - kubectl create -f kube-prometheus/manifests/setup
      - kubectl apply -f kube-prometheus/manifests/
      - rm -rf kube-prometheus
    preconditions:
      - sh: sh -c "! kubectl get ns monitoring"
    silent: true

  instalar-monitoramento:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Instalando monitoramento..."
      - helm uninstall monitoramento --namespace monitoring || true
      - helm install monitoramento monitoring/

  deploy-k8s-cluster:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Provisionando cluster Kubernetes..."
      - doctl kubernetes cluster create desafio-pick --region ams3 --version 1.30.4-do.0  --node-pool "name=nodepool;size=s-2vcpu-4gb;count=3" --1-clicks ingress-nginx

  destroy-k8s-cluster:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - echo "Destruindo cluster Kubernetes..."
      - doctl kubernetes cluster delete desafio-pick --force

  gerar-env:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      COSIGN_PASSWORD:
        sh: export LC_CTYPE=c; cat /dev/urandom | tr -dc 'a-zA-Z0-9-!@#$%&*_+' | fold -w 24 | head -n1
    cmds:
      - echo "Gerando senha para o Cosign..."
      - echo "COSIGN_PASSWORD='{{.COSIGN_PASSWORD}}'" > .env
    silent: true
    status:
      - test -f .env

  gerar-chave-cosign:
    dir: '{{.TASKFILE_DIR}}'
    deps:
      - gerar-env
    dotenv: [ .env ]
    preconditions:
      - test -f .env
    cmds:
      - echo "Gerando chaves do Cosign..."
      - cosign generate-key-pair --output-key-prefix $COSIGN_KEY_PATH
    silent: true
    status:
      - test -f $COSIGN_KEY_PATH.key
      - test -f $COSIGN_KEY_PATH.pub

  assinar-imagem:*:
    deps:
      - gerar-chave-cosign
    dotenv:
      - .env
      - .env-docker
    dir: '{{.TASKFILE_DIR}}'
    vars:
        TAG: '{{index .MATCH 0}}'
    preconditions:
      - sh: docker login -u {{.REGISTRY_USER}} --password-stdin <<< ${DOCKER_TOKEN}
    cmds:
      - echo "Assinando imagem..."
      - cosign sign --yes --key {{.COSIGN_KEY_PATH}}.key ${REGISTRY_USER}/${IMAGE_NAME}:{{.TAG}}

  build-docker-image:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      TAG: '{{index .MATCH 0}}'
    cmds:
      - echo "Construindo imagem Docker..."
      - docker build -t ${IMAGE_NAME}:{{.TAG}} .

  push-docker-image:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      TAG: '{{index .MATCH 0}}'
    preconditions:
      - sh: docker login -u {{.REGISTRY_USER}} --password-stdin <<< ${DOCKER_TOKEN}
    cmds:
      - task: gerar-chave-cosign
      - echo "Fazendo o push da imagem Docker..."
      - docker tag {{.IMAGE_NAME}}:{{.TAG}}-amd64 {{.REGISTRY_USER}}/{{.IMAGE_NAME}}:{{.TAG}}
      - docker push {{.REGISTRY_USER}}/{{.IMAGE_NAME}}:{{.TAG}}
      - task: assinar-imagem:{{.TAG}}

  gerar-chave-melange:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - docker run --rm -v "${PWD}":/work cgr.dev/chainguard/melange keygen
    status:
      - test -f melange.rsa

  melange-build:
    dir: '{{.TASKFILE_DIR}}'
    deps:
      - gerar-chave-melange
    cmds:
      - docker run --privileged --rm -v "${PWD}":/work cgr.dev/chainguard/melange build melange.yaml --arch amd64 --signing-key melange.rsa

  apko-build:*:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      IMAGE_NAME: '{{index .MATCH 0}}'
      TAG: '{{index .MATCH 1}}'
    cmds:
      - docker run --rm --workdir /work -v ${PWD}:/work cgr.dev/chainguard/apko build apko.yaml {{.IMAGE_NAME}}:{{.TAG}} {{.IMAGE_NAME}}.tar --arch amd64
      - docker load < {{.IMAGE_NAME}}.tar
      - task: push-docker-image:{{.TAG}}
      - task: clean-up:{{.IMAGE_NAME}}

  clean-up:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      IMAGE_NAME: '{{index .MATCH 0}}'
    cmds:
      - rm -f {{.IMAGE_NAME}}.tar

  instalar-helm:*:*:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      RELEASE_NAME: '{{index .MATCH 0}}'
      RELEASE_NAMESPACE: '{{index .MATCH 1}}'
      CHART_PATH: 'giropops-senhas-chart'
      RELEASE_VERSION: '{{index .MATCH 2}}'
    cmds:
      - helm uninstall {{.RELEASE_NAME}} --namespace {{.RELEASE_NAMESPACE}} || true
      - helm install {{.RELEASE_NAME}} --create-namespace --namespace {{.RELEASE_NAMESPACE}} oci://registry-1.docker.io/$REGISTRY_USER/{{.CHART_PATH}} --version {{.RELEASE_VERSION}}

  atualizar-helm:*:*:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      RELEASE_NAME: '{{index .MATCH 0}}'
      RELEASE_NAMESPACE: '{{index .MATCH 1}}'
      CHART_PATH: 'giropops-senhas-chart'
      CHART_VERSION: '{{index .MATCH 2}}'
    cmds:
      - helm upgrade {{.RELEASE_NAME}} --namespace {{.RELEASE_NAMESPACE}} oci://registry-1.docker.io/$REGISTRY_USER/{{.CHART_PATH}} --version {{.CHART_VERSION}}

  publicar-helm:*:
    dir: '{{.TASKFILE_DIR}}'
    vars:
      CHART_PATH: '{{index .MATCH 0}}'
    cmds:
      - helm package {{.CHART_PATH}}
      - helm push {{.CHART_PATH}}*.tgz oci://registry-1.docker.io/$REGISTRY_USER/
      - rm -f {{.CHART_PATH}}*.tgz