apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giropops-senhas
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: /probe
      port: "9115"
  selector:
    matchLabels:
        app.kubernetes.io/instance: giropops-senhas
        app.kubernetes.io/name: giropops-senhas-chart