apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  labels:
    app: blackbox-exporter
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: [200]
