apiVersion: v1
kind: Service
metadata:
  name: {{ include "giropops-senhas-chart.fullname" . }}
  labels:
    {{- include "giropops-senhas-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "giropops-senhas-chart.selectorLabels" . | nindent 4 }}
